# Library

In [ ]:
#Kedua library ini digunakan untuk mengunduh dan mengekstrak file zip jika diperlukan.
import zipfile
import urllib.request
#Library ini digunakan untuk melakukan manipulasi dan ekstraksi fitur dari gambar menggunakan GLCM (Grey-Level Co-occurrence Matrix).
from skimage.transform import resize
from skimage.io import imread
from skimage.feature import greycomatrix, greycoprops
#Library ini digunakan untuk bekerja dengan gambar menggunakan format PIL (Python Imaging Library).
from PIL import Image, ImageOps
#Library ini digunakan untuk manipulasi dan visualisasi data.
import numpy as np
import matplotlib.pyplot as plt
#Library ini digunakan untuk pemrosesan gambar menggunakan OpenCV.
import cv2
#Library ini digunakan untuk analisis data .
import pandas as pd
#Library ini digunakan untuk mengakses dan memanipulasi sistem file.
import os
from pathlib import Path

# Load Data

In [ ]:
# digunakan untuk menghubungkan dan mengakses Google Drive ke dalam sesi Google Colab
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
Categories=['Abror','Ade','Adee','Adin','Adriana','Aji','Akbar','Akri','Aldi','Aldy','Alfa','Ammanda','Andi','Anggi','Arief','Arif','Ariff','Arya','Audi','Audii','Ayu','Aziz','Bagas','Bayu','Berlin','Berliyan','Calvin','Cantika','Chandra','Chintami','Cikal','Clara','Claraa','Clifansi','Debi','Deta','Devi','Dharma','Dian','Dickey','Diky','Dinara','Diva','Dwi','Dypen','Eka','Ekaa','Elvina','Enda','Erick','Fadira','Fadly','Fani','Farikha','Faris','Fenika','Ferli','Fikho','Fikri','Firda','Geyma','Gigih','Gilang','Haidar','Hana','Hanif','Heri','Ica','Ika','Indah','Indri','Intan','Iqbal','Irfan','Jefri','Julian','Karina','Kasnadi','Khairunnisa','Kholifa','Leo','Lina','Lisda','Luffy','Luki','Made','Maulidina','Merni','Micko','Miko','Naofal','Naufal','Nisa','Nova','Nyoman','Oktavia','Patra','Putri','Putu','Qieza','Raflan','Rafli','Raflii','Rahel','Rahman','Raka','Raldo','Regita','Rendy','Rere','Resti','Restu','Resty','Reza','Ridho','Ridhoo','Rifqi','Rio','Risa','Risma','Romza','Safa','Sarina','Sarip','Satya','Sefia','Selvia','Septian','Sheila','Sinlan','Tamara','Taufiq','Tegar','Teo','Tia','Tias','Tirta','Trisna','Tya','Uki','Vella','Vera','Verlando','Wendi','Willy','Yoga','Yolanda','Yongki','Zaky','Zidan']
datadir='/content/drive/MyDrive/lulus'
target_arr=[]
label=[]
imgs=[]
for i in Categories:
    print(f'loading... category : {i}')
    path=os.path.join(datadir,i)
    for img in os.listdir(path):
      if (os.path.join(path,img).endswith('.png')):
        label.append(i)
        img = cv2.imread(os.path.join(path, img))
        gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        resize = cv2.resize(gray, dsize=(150, 150))
        imgs.append(resize)
        target_arr.append(Categories.index(i))
    print(f'loaded category:{i} successfully')
target=np.array(target_arr)

loading... category : Abror
loaded category:Abror successfully
loading... category : Ade
loaded category:Ade successfully
loading... category : Adee
loaded category:Adee successfully
loading... category : Adin
loaded category:Adin successfully
loading... category : Adriana
loaded category:Adriana successfully
loading... category : Aji
loaded category:Aji successfully
loading... category : Akbar
loaded category:Akbar successfully
loading... category : Akri
loaded category:Akri successfully
loading... category : Aldi
loaded category:Aldi successfully
loading... category : Aldy
loaded category:Aldy successfully
loading... category : Alfa
loaded category:Alfa successfully
loading... category : Ammanda
loaded category:Ammanda successfully
loading... category : Andi
loaded category:Andi successfully
loading... category : Anggi
loaded category:Anggi successfully
loading... category : Arief
loaded category:Arief successfully
loading... category : Arif
loaded category:Arif successfully
loading.

# Proses GLCM

In [ ]:
def calc_glcm_sudut90(img, label, props=['contrast', 'homogeneity', 'energy', 'correlation'], dists=[1], lvl=256, sym=True, norm=True):
    agls = [np.pi/2]
    glcm = greycomatrix(img,
                        distances=dists,
                        angles=agls,
                        levels=lvl,
                        symmetric=sym,
                        normed=norm)
    feature = []
    glcm_props = [prop for name in props for prop in greycoprops(glcm, name)[0]]
    for item in glcm_props:
        feature.append(item)
    feature.append(label)

    return feature

In [ ]:
properties = ['contrast', 'homogeneity', 'energy', 'correlation']

glcm_all_agls = []
for img, label in zip(imgs, label):
    glcm_all_agls.append(
            calc_glcm_sudut90(img,
                              label,
                              props=properties)
                            )

columns = []
angles = ['90']
for name in properties :
    for ang in angles:
        columns.append(name + "_" + ang)

columns.append("label")

Output streaming akan dipotong hingga 5000 baris terakhir.
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:35: skimage_deprecation: Function ``greycomatrix`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycomatrix`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_version='1.0')
/usr/local/lib/python3.10/dist-packages/skimage/feature/__init__.py:42: skimage_deprecation: Function ``greycoprops`` is deprecated and will be removed in version 1.0. Use ``skimage.feature.graycoprops`` instead.
  removed_ve

In [ ]:
# Membuat DataFrame dari data GLCM
df = pd.DataFrame(glcm_all_agls, columns=columns)
df

contrast_90  homogeneity_90  energy_90  correlation_90  label
0      181.245011        0.931360   0.919506        0.850129  Abror
1      167.793468        0.949249   0.942797        0.829454  Abror
2      184.579508        0.942866   0.937557        0.815824  Abror
3      137.332528        0.953745   0.947441        0.850919  Abror
4      172.062371        0.945995   0.938108        0.781004  Abror
...           ...             ...        ...             ...    ...
1495   340.801611        0.857350   0.837638        0.859516  Zidan
1496   362.555705        0.898833   0.886687        0.784706  Zidan
1497   285.566174        0.925350   0.917304        0.808980  Zidan
1498   285.599732        0.941339   0.936658        0.787745  Zidan
1499   448.650470        0.903614   0.895569        0.779803  Zidan

[1500 rows x 5 columns]

# Proses

In [ ]:
dff = pd.read_csv('GLCM90.csv')

# Pembagian Data

In [ ]:
x = dff.drop('label', axis=1)
y = dff['label']

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20,random_state=0)

# Euclidean Distance

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import cross_val_score

In [ ]:
knn_euclidean = KNeighborsClassifier(n_neighbors=9, metric='euclidean')

In [ ]:
knn_euclidean.fit(x_train, y_train)

KNeighborsClassifier(metric='euclidean', n_neighbors=9)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data train
y_pred = knn_euclidean.predict(x_train)

# Menghitung confusion matrix
cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_train, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_train, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))


Confusion Matrix:
[[3 2 0 ... 0 0 0]
 [3 3 1 ... 0 0 0]
 [2 2 4 ... 0 0 0]
 ...
 [0 0 0 ... 6 1 0]
 [0 0 0 ... 0 5 0]
 [0 0 0 ... 2 2 0]]
Accuracy: 66.75%
Precision: 65.50%
Recall: 65.82%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data test
y_pred = knn_euclidean.predict(x_test)

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_test, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_test, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))

Confusion Matrix:
[[1 4 0 ... 0 0 0]
 [0 2 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]]
Accuracy: 54.00%
Precision: 49.80%
Recall: 55.42%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Manhatan Distance

In [ ]:
# KNN dengan metrik Manhattan
knn_manhattan = KNeighborsClassifier(n_neighbors=9, metric='manhattan')

In [ ]:
knn_manhattan.fit(x_train, y_train)

KNeighborsClassifier(metric='manhattan', n_neighbors=9)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data train
y_pred = knn_manhattan.predict(x_train)

# Menghitung confusion matrix
cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_train, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_train, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))


Confusion Matrix:
[[3 2 0 ... 0 0 0]
 [2 5 0 ... 0 0 0]
 [1 2 5 ... 0 0 0]
 ...
 [0 0 0 ... 7 1 0]
 [0 0 0 ... 0 7 0]
 [0 0 0 ... 2 2 0]]
Accuracy: 75.50%
Precision: 76.31%
Recall: 74.49%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data test
y_pred = knn_manhattan.predict(x_test)

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_test, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_test, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))

Confusion Matrix:
[[2 3 0 ... 0 0 0]
 [0 2 1 ... 0 0 0]
 [0 0 2 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 2 0]
 [0 0 0 ... 0 1 0]]
Accuracy: 64.00%
Precision: 59.57%
Recall: 64.45%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Minkowski Distance

In [ ]:
# KNN dengan metrik Minkowski (p=2, sama dengan Euclidean)
knn_minkowski = KNeighborsClassifier(n_neighbors=9, metric='minkowski', p=3)

In [ ]:
knn_minkowski.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=9, p=3)

In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data train
y_pred = knn_minkowski.predict(x_train)

# Menghitung confusion matrix
cm = confusion_matrix(y_train, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_train, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_train, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_train, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))

Confusion Matrix:
[[3 2 0 ... 0 0 0]
 [3 3 1 ... 0 0 0]
 [2 2 4 ... 0 0 0]
 ...
 [0 0 0 ... 5 1 0]
 [0 0 0 ... 0 5 0]
 [0 0 0 ... 2 2 0]]
Accuracy: 63.83%
Precision: 61.31%
Recall: 62.82%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [ ]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score

# Menghitung prediksi model pada data test
y_pred = knn_minkowski.predict(x_test)

# Menghitung confusion matrix
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(cm)

# Menghitung akurasi
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy: {:.2f}%".format(accuracy * 100))

# Menghitung presisi
precision = precision_score(y_test, y_pred, average='macro')
print("Precision: {:.2f}%".format(precision * 100))

# Menghitung recall
recall = recall_score(y_test, y_pred, average='macro')
print("Recall: {:.2f}%".format(recall * 100))

Confusion Matrix:
[[1 4 0 ... 0 0 0]
 [0 2 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 ...
 [0 0 0 ... 2 0 0]
 [0 0 0 ... 1 1 0]
 [0 0 0 ... 0 1 0]]
Accuracy: 52.00%
Precision: 47.82%
Recall: 53.02%


/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# Testing Model

In [ ]:
import cv2
from google.colab.patches import cv2_imshow
import re

file_path = '/content/Abror5.png'
file_name = file_path.split('/')[-1]
file_name_without_extension = file_name.split('.')[0]
match = re.search(r'\d+', file_name_without_extension)
target = int(match.group())
img = cv2.imread(file_path)
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
resized = cv2.resize(gray, (150, 150))
glcm = greycomatrix(resized, [1], [np.pi/2], 256, symmetric=True, normed=True)
contrast = greycoprops(glcm, 'contrast')[0, 0]
homogeneity = greycoprops(glcm, 'homogeneity')[0, 0]
energy = greycoprops(glcm, 'energy')[0, 0]
correlation = greycoprops(glcm, 'correlation')[0, 0]
import pandas as pd
data = { 'contrast_90': [contrast], 'homogeneity_90': [homogeneity], 'energy_90': [energy], 'correlation_90': [correlation] }
test = pd.DataFrame(data)

error: ignored

In [ ]:
probabilitas = knn.predict_proba(test)
cv2_imshow(resized)
# Analisis hasil probabilitas
for i, prob in enumerate(probabilitas):
    kelas_probabilitas = zip(knn.classes_, prob)
    for cls, proba in kelas_probabilitas:
        if proba > 0:  # Cek apakah probabilitas lebih besar dari 0 untuk output label
            print(f"Tanda Tangan Punya {cls}: {proba*100}%")
prediksi_label = knn.classes_[np.argmax(probabilitas)]

In [ ]:
print("Hasil Tanda Tangan : ",prediksi_label)